# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# Usually you shouldn't need to change the first part of the file

# DO NOT CHANGE THE CODE BELOW
before_install:
  - sudo apt-get update -y
  - sudo apt-get install libgit2-dev
  - sudo apt-get install pip
  - rvm install 2.5.3
  - rvm 2.5.3 do ruby -S gem install jekyll
  - R -q -e 'install.packages(c("remotes", "curl"))'
  - R -q -e 'remotes::install_github("hadley/requirements")'
install:
  - pip install pyyaml
script:
  - make lesson-check-all
  - make --always-make site


# Header
language: r
sudo: false
dist: xenial
cache: packages
latex: false

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

#services
services:
