before_install:
  - sudo apt-get update -y
  - sudo apt-get install libgit2-dev libudunits2-dev
  - sudo apt-get install python3-setuptools python3-pip
  - rvm install 2.5.3
  - rvm 2.5.3 do ruby -S gem install bundle
  - R -q -e 'install.packages(c("remotes", "curl"))'
  - R -q -e 'remotes::install_github("hadley/requirements")'
install:
  - sudo -H pip3 install pyyaml
script:
  - bundle install
  - make lesson-check-all
  - make --always-make site


# Header
language: r
sudo: false
cache: packages
latex: false

branches:
  only:
  - gh-pages

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  #- MAKEFLAGS="-j 2"

# Add spellchecking for PRs
jobs:
  include:
    - stage: spelling
      language: python
      sudo: true
      python: "3.6"
      # The default before_install step is slow because of ruby and unnecessary for spellchecking
      before_install:
      install:
        # Use codespell for spell checking
        sudo pip install codespell
      script:
        # Run a non-erroring version to report spelling errors using standard filters
        echo -e "\nRunning codespell with standard filters (returns 0)\n"

        echo -e "\n\nRunning codespell with custom filters (returns errorcode)\n"

    - stage: check_and_build
